### ISSUE TITLE
Failed to build/run

### ISSUE THREAD

**Issue by bjornwgnr** [parity-js/light#46]
```
Bjorns-MacBook-Pro:light bjorn$ yarn electron
yarn run v1.3.2
$ yarn build
$ lerna run build
lerna info version 2.11.0
lerna ERR! build Errored while running script in 'light-hoc'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run build
lerna ERR! error An unexpected error occurred: "micromatch.matcher(): pattern should be a string, regex, or function.".
lerna ERR! info If you think this is a bug, please open a bug report with the information provided in "/Users/bjorn/Downloads/git/light/packages/light-hoc/yarn-error.log".
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
lerna ERR! build Errored while running script in 'light-ui'
{ Error: Command failed: yarn run build
error An unexpected error occurred: "micromatch.matcher(): pattern should be a string, regex, or function.".
info If you think this is a bug, please open a bug report with the information provided in "/Users/bjorn/Downloads/git/light/packages/light-hoc/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: 'info If you think this is a bug, please open a bug report with the information provided in "/Users/bjorn/Downloads/git/light/packages/light-hoc/yarn-error.log".\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'error An unexpected error occurred: "micromatch.matcher(): pattern should be a string, regex, or function.".\n',
  failed: true,
  signal: null,
  cmd: 'yarn run build',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by amaurymartiny** [comment]
@bjornwgnr This is a yarn version error, you need at least yarn 1.4.2

You can get the latest 1.7.0 here: https://yarnpkg.com/en/docs/install

**Comment by bjornwgnr** [comment]
Works, cheers!
